apiVersion: v1
kind: ConfigMap
metadata:
  name: open-match-configmap-override
  namespace: open-match
  labels:
    app: open-match-customize
data:
  matchmaker_config_override.yaml: |
    api:
      evaluator:
        hostname: "skulls-ludo-evaluator.default.svc.cluster.local"
        grpcport: 50508
    synchronizer:
      enabled: true
      registrationIntervalMs: 1500
      proposalCollectionIntervalMs: 3000
