apiVersion: v1
kind: ConfigMap
metadata:
  name: open-match-override-configmap
  namespace: open-match
  labels:
    app: open-match-customize
data:
  matchmaker_config_override.yaml: |
    api:
      evaluator:
        hostname: "skulls-ludo-evaluator.default.svc.cluster.local"
        grpcport: 50508
    # Synchronizer tuning
    registrationIntervalMs: 1500
    proposalCollectionIntervalMs: 3000
